name: hobo_test
description: A new Flutter application.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  smooth_page_indicator: ^0.2.3
  line_icons: ^2.0.1
  ionicons: ^0.1.2
  flutter_svg: ^0.22.0
  shared_preferences: ^2.0.5
  provider: ^5.0.0
  flutter_swiper: ^1.1.6
  flutter_rating_bar: ^4.0.0
  expandable_page_view: ^1.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true

  assets:
   - assets/images/Onboarding-1.svg
   - assets/images/Onboarding-2.svg
   - assets/images/Onboarding-3.svg
   - assets/images/Tourist-background.svg
   - assets/images/Tourist-girl.svg
   - assets/images/Guide-background.svg
   - assets/images/Guide-girl.svg
   - assets/images/Guide-girl-dark.svg
   - assets/images/Tourist-girl-dark.svg
   - assets/images/provaSocial.jpeg
   - assets/images/Paris-Background.png
   - assets/images/Paris-Monument.png
   - assets/images/NewYork-Background.png
   - assets/images/NewYork-Monument.png
   - assets/images/Paris-Background_Big.png
   - assets/images/Paris-Monument_Big.png
   - assets/images/Paris-Tour.png
   - assets/images/CreditCard.png
   - assets/images/cardIcon.svg
   - assets/images/stripe.svg
   - assets/images/paypal.svg
   - assets/images/applepay.svg
   - assets/images/hoboClear.svg
   - assets/images/hoboColor.svg
   - assets/images/background-profile.png
   - assets/images/translate.svg
   - assets/images/trophy.svg
   - assets/images/Google-Logo.svg
   - assets/images/image-social-1.png

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Black.ttf
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 700
        - asset: assets/fonts/Poppins-Light.ttf
          weight: 300
        - asset: assets/fonts/Poppins-Regular.ttf
        - asset: assets/fonts/Poppins-SemiBold.ttf
          weight: 600
    - family: CenturyGothic
      fonts:
        - asset: assets/fonts/CenturyGothic-Bold.ttf

    - family: CustomIcons
      fonts:
        - asset: assets/fonts/CustomIcons.ttf
